// UI/svelte/src/CurrencyConverterContainer.svelte
<script>
    import CurrencyConverter from "./CurrencyConverter.svelte";
    import CurrencyConverterService from "./CurrencyConverterService";

    const currencies = [
        {code: "USD", name: "United States Dollar"},
        {code: "CAD", name: "Canadian Dollar"},
        {code: "MXN", name: "Mexican Pesos"}
    ];
    let fromCountryCode = $state("USD");
    let toCountryCode = $state("CaD");
    let fromAmount = $state(0);
    let toAmount = $state(0);

</script>

<CurrencyConverter
        currencies={currencies}
        fromAmount={fromAmount}
        fromCountryCode={fromCountryCode}
        onConversionRequested="{ async () => {
            toAmount = await CurrencyConverterService(fromCountryCode, toCountryCode, fromAmount);
        }}"
        onFromAmountChanged="{value => { fromAmount = value; toAmount= 0; }}"
        onFromCountryCodeChanged="{value => { fromCountryCode = value; toAmount= 0; }}"
        onToCountryCodeChanged="{value => { toCountryCode = value; toAmount= 0; }}"
        toAmount={toAmount}
        toCountryCode={toCountryCode}
/>

<style>

</style>

// UI/react/src/CurrencyConverterContainer.jsx
import CurrencyConverter from "./CurrencyConverter.jsx";
import CurrencyConverterService from "./CurrencyConverterService";
import {useEffect, useState} from "react";

function CurrencyConverterContainer  (){
const currencies = [
    { code: "USD", name: "United States Dollars" },
    { code: "CAD", name: "Canadian Dollars" },
    { code: "MXN", name: "Mexican Pesos" }
];
const [fromCountryCode, setFromCountryCode] = useState("USD");
const [toCountryCode, setToCountryCode] = useState("CaD");
const [fromAmount, setFromAmount] = useState("");
const [toAmount, setToAmount] = useState("");

        return (
            <CurrencyConverter
                currencies={currencies}
                fromAmount={fromAmount}
                toAmount={toAmount}
                fromCountryCode={fromCountryCode}
                toCountryCode={toCountryCode}
                onFromAmountChanged={fromAmount => {
                    setFromAmount(fromAmount);
                    setToAmount(null);
                }}
                onFromCountryCodeChanged={fromCountryCode => {
                    setFromCountryCode(fromCountryCode);
                    setToAmount(null);
                }}
                onToCountryCodeChanged={toCountryCode => {
                    setToCountryCode(toCountryCode);
                    setToAmount(null);
                }}
                onConversionRequested={async () => {
                    const toAmount = await CurrencyConverterService(
                        fromCountryCode,
                        toCountryCode,
                        fromAmount
                    );
                    setToAmount(toAmount);
                }}
            />
        );



}

export default CurrencyConverterContainer;
