// UI/src/CurrencySelection.jsx
const CurrencySelection = ({ currencies, selectedValue, onCurrencySelected }) => {
    return (
        <select
            value={selectedValue}
            onChange={e => onCurrencySelected(e.target.value)}
        >
            {currencies.map(c => (
                <option key={c.code} value={c.code}>
                    {c.name} ({c.code})
                </option>
            ))}
        </select>
    );
};

export default CurrencySelection;

// UI/svelte/src/CurrencySelection.svelte
<script>
    let {currencies, selectedValue, onCurrencySelected} = $props();
</script>

<select
        onchange="{ e => onCurrencySelected(e.target.value) }"
        value="{selectedValue}">
    {#each currencies as c}
        <option value="{c.code}">{c.name}</option>
    {/each}
</select>

<style>

</style>
